### ISSUE TITLE
Make the label of the note bigger

### ISSUE THREAD

**Issue by Suzie97** [davidgolding/obsidian-big-sur-aesthetic#2]
Hey, I feel like the note title is too small. I think, it would be better if it were a little bigger.

**Comment by 0ge** [comment]
You can try the following [CSS snippet](https://help.obsidian.md/Advanced+topics/Customizing+CSS) in the meantime. Its the "Large title" from the [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/typography/)

```css
.workspace-leaf-content .view-header-title, .workspace-leaf.mod-active .workspace-leaf-content .view-header-title {
	font-size: 26px;
	font-weight: bold;
}
```
